language: perl
perl:
    - '5.18'
env:
    - BACKEND=moar
    - BACKEND=jvm
    - BACKEND=parrot 
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda  
install:
    - panda --notests install . # installs deps
before_script:
    - panda list --installed --verbose
script:
    - prove -e perl6 -lrv t/ 
after_success:
#   do coveralls.io testing
