language: perl
perl:
    - '5.18'
env:
    - BACKEND=moar
    - BACKEND=jvm
    - BACKEND=parrot 
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda  
install:
    - panda-fetch . # install deps
before_script:
    - panda list --installed --verbose
script:
    - panda-build
    - panda-test # panda will test against compiled /blib, and prove against /lib
    - prove -v -s -j$(test-jobs) -e "perl6 --ll-exception -Ilib" $(test-files)
after_success:
#   do coveralls.io testing?
